version = 0.1

[default.global.parameters]
s3_prefix = "pace-data-api-cf"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"

[dev.deploy.parameters]
stack_name = "pace-data-api-dev"
s3_bucket = "pace-data-api-sam-cli-dev"
region = "us-east-1"
s3_prefix = "pace-data-api-sam-cli-dev-cf"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"

[stage.deploy.parameters]
stack_name = "pace-data-api-stg"
s3_bucket = "pace-data-api-sam-cli-stg"
region = "us-east-2"
s3_prefix = "pace-data-api-sam-cli-stg-cf"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"

[prod.deploy.parameters]
stack_name = "pace-data-api-prod"
s3_bucket = "pace-data-api-sam-cli-prod"
region = "us-west-2"
s3_prefix = "pace-data-api-sam-cli-prod-cf"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
